import type { MetaOAuthState } from '../models/MetaConnection.js';

/**
 * Port — short-lived, single-use OAuth `state` store.
 *
 * `state` is the CSRF guard for the Embedded Signup redirect/popup: it is
 * generated by the tenant-api, bound to the initiating tenant + user, and
 * consumed exactly once at `complete`. A replayed or foreign state must be
 * rejected, otherwise an attacker could inject their own WABA into a victim's
 * tenant.
 */
export interface IOAuthStateStore {
  /** Persist state -> {tenantId, userId} with a TTL. */
  issue(tenantId: string, userId: string): Promise<MetaOAuthState>;

  /**
   * Atomically consume a state. Returns the bound record on first use, or null
   * if the state is unknown, expired, or already consumed.
   */
  consume(state: string): Promise<MetaOAuthState | null>;
}
