import type { Tenant } from '../models/Tenant.js';

export interface CreateTenantInput {
  /**
   * Generated by the caller, not by the database default. `tenants` is under
   * FORCE ROW LEVEL SECURITY and its policy is `id = app.tenant_id`, so the
   * context has to be established *before* the INSERT — which is only possible
   * if the id is known first (audit finding H1).
   */
  id: string;
  name: string;
  slug: string;
}

export interface UpdateTenantInput {
  name?: string;
  wabaId?: string;
  phoneNumberId?: string;
  accessToken?: string | null;
}

export interface ITenantRepo {
  findById(id: string): Promise<Tenant | null>;
  /**
   * Resolve a tenant from its slug. Runs through the SECURITY DEFINER function
   * `lookup_tenant_by_slug` because login has no tenant context yet and
   * migration 007 puts `tenants` under FORCE ROW LEVEL SECURITY. The function
   * returns id/slug/status only — never the access token.
   */
  findBySlug(slug: string): Promise<Tenant | null>;
  /**
   * The id of the tenant that has bound a given Meta phone number id, or null.
   *
   * Deliberately returns only the id: it feeds the onboarding conflict check
   * (another tenant already claimed the number) and the gateway's webhook
   * routing, neither of which needs anything else from the row. Goes through
   * the SECURITY DEFINER function `tenant_id_for_phone`.
   */
  findTenantIdByPhoneNumberId(phoneNumberId: string): Promise<string | null>;
  create(input: CreateTenantInput): Promise<Tenant>;
  update(id: string, input: UpdateTenantInput): Promise<Tenant>;
}
